### ISSUE TITLE
NoSuchElementException in checkRemoveCommittedEntry when copying values of TX view map

### ISSUE THREAD

**Issue by JanWiemer** [JanWiemer/jacis#14]
Version: 2.0.1:

Under heavy load the following exception occured:

```
Caused by: java.util.NoSuchElementException
    at org.jacis.util.ConcurrentWeakHashMap$HashIterator.nextEntry(ConcurrentWeakHashMap.java:1231)
    at org.jacis.util.ConcurrentWeakHashMap$ValueIterator.next(ConcurrentWeakHashMap.java:1266)
    at java.base/java.util.AbstractCollection.toArray(AbstractCollection.java:144)
    at java.base/java.util.ArrayList.<init>(ArrayList.java:179)
    at org.jacis.store.JacisStoreImpl.checkRemoveCommittedEntry(JacisStoreImpl.java:557)
    at org.jacis.store.StoreTxDemarcationExecutor.executeCommit(StoreTxDemarcationExecutor.java:115)
    at org.jacis.store.JacisStoreImpl.lambda$internalCommit$20(JacisStoreImpl.java:485)
    at org.jacis.store.JacisStoreImpl.lambda$runnableWrapper$24(JacisStoreImpl.java:596)
    at org.jacis.store.JacisStoreImpl.withWriteLock(JacisStoreImpl.java:579)
    at org.jacis.store.JacisStoreImpl.internalCommit(JacisStoreImpl.java:485)
    at org.jacis.container.JacisContainer.internalCommit(JacisContainer.java:522)
    at org.jacis.plugin.txadapter.jta.AbstractJacisTransactionAdapterJTA$JacisSync.afterCompletion(AbstractJacisTransactionAdapterJTA.java:199)
```

**Comment by JanWiemer** [comment]
fixed with release 2.02
