### ISSUE TITLE
ConcurrentModificationException in JacisIndexRegistry.getFromNonUniqueIndexReadOnly

### ISSUE THREAD

**Issue by ssipaul** [JanWiemer/jacis#38]
Following exception occured:

Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1628)
	at org.jacis.index.JacisIndexRegistry.getFromNonUniqueIndexReadOnly(JacisIndexRegistry.java:334)
	at org.jacis.index.JacisNonUniqueIndex.getReadOnly(JacisNonUniqueIndex.java:59)

It seems that the nonUniqueIndexDataMap is initilized with a simple HashSet instead of a ConcurrentHashSet in method org.jacis.index.JacisIndexRegistry#trackModificationAtNonUniqueIndex. Changing this to ConcurrentHashSet should fix the issue.

**Comment by JanWiemer** [comment]
Fixed in 2.1.7
